#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET

api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint